server:
  port: 1919

spring: 
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: BENEFICIARYSERVICE
              uri: lb://BENEFICIARYSERVICE
              predicates:
                - Path=/BENEFICIARYSERVICE/**
            - id: FINANCESERVICE
              uri: lb://FINANCESERVICE
              predicates:
                - Path=/FINANCESERVICE/** 

eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true  
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance: 
    hostname: localhost